@_04_CRUD_HostAddress = http://localhost:5179

GET {{_04_CRUD_HostAddress}}/weatherforecast/
Accept: application/json

###
GET  http://localhost:5179/api/categories?Val="electronics"

###
GET  http://localhost:5179/api/categories

###

POST http://localhost:5179/api/categories
Content-Type: application/json  

{
    "name" : "electronics",
    "description": "Items related to food and household supplies"
}

###

DELETE http://localhost:5179/api/categories/5ce5f9cb-2f0f-4a16-b94b-dbac4e9f8660

###

PUT http://localhost:5179/api/categories/5ce5f9cb-2f0f-4a16-b94b-dbac4e9f8660
Content-Type: application/json  

{
    "name": "Gadgets",
    "description": "Updated description for gadgets category"
}
